// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.5
// source: spike.proto

package grpcService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TestGRPCService_TestGRPC_FullMethodName = "/grpcService.TestGRPCService/TestGRPC"
)

// TestGRPCServiceClient is the client API for TestGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestGRPCServiceClient interface {
	TestGRPC(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type testGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestGRPCServiceClient(cc grpc.ClientConnInterface) TestGRPCServiceClient {
	return &testGRPCServiceClient{cc}
}

func (c *testGRPCServiceClient) TestGRPC(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, TestGRPCService_TestGRPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestGRPCServiceServer is the server API for TestGRPCService service.
// All implementations must embed UnimplementedTestGRPCServiceServer
// for forward compatibility
type TestGRPCServiceServer interface {
	TestGRPC(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedTestGRPCServiceServer()
}

// UnimplementedTestGRPCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestGRPCServiceServer struct {
}

func (UnimplementedTestGRPCServiceServer) TestGRPC(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestGRPC not implemented")
}
func (UnimplementedTestGRPCServiceServer) mustEmbedUnimplementedTestGRPCServiceServer() {}

// UnsafeTestGRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestGRPCServiceServer will
// result in compilation errors.
type UnsafeTestGRPCServiceServer interface {
	mustEmbedUnimplementedTestGRPCServiceServer()
}

func RegisterTestGRPCServiceServer(s grpc.ServiceRegistrar, srv TestGRPCServiceServer) {
	s.RegisterService(&TestGRPCService_ServiceDesc, srv)
}

func _TestGRPCService_TestGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestGRPCServiceServer).TestGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestGRPCService_TestGRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestGRPCServiceServer).TestGRPC(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// TestGRPCService_ServiceDesc is the grpc.ServiceDesc for TestGRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestGRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcService.TestGRPCService",
	HandlerType: (*TestGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestGRPC",
			Handler:    _TestGRPCService_TestGRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spike.proto",
}
